Remember outside temperature for Siemianowice and Nowy Paderewskiego.
wruz/ihg pull request #37
Opened 2019-10-05 12:18 UTC by DonMarcino

Dodałem zapisywanie "temperatura na zewnątrz" do SharedPreferences dla Siemianowice i Nowy Paderewskiego.

2019-10-05 12:59 UTC, arkadiuszrutkowski requested changes
@DonMarcino zauważyłem buga - Klucz "tempOutside" jest powiązany ze starym formularzem Paderewskiego i w rezultacie Siemanowice i Paderewskiego współdzielą ze sobą to samo. Powinno być oddzielnie zapisane dla każdego formularza: "tempOutsideSiemanowice"/"tempOutsideNewPaderewskiego".

Dodatkowo sugeruję jakoś te klucze do stałych wyodrębnić, by można było ew. w przyszłości się do nich odwołać, aby nie popełnić literówek lub copy/paste faila.

2019-10-05 13:00 UTC, arkadiuszrutkowski commented
PS - Przy czym nazwę "tempOutside" dla Paderewskiego zostawiamy taką jaka jest, bo inaczej zerwałoby z kompatybilnością danych u klienta.

2019-10-05 23:47 UTC, DonMarcino commented
Dałem poprawkę i wydzieliłem wszystkie klucze "shared preferences" do klasy Utils.

2019-10-06 09:19 UTC, arkadiuszrutkowski approved these changes

2019-10-06 09:19 UTC, merged